version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Migration Runner (Runs once then exits)
  migrate:
    build:
      context: .
      dockerfile: ./packages/database/Dockerfile.migrate
    container_name: todo-migrate
    environment:
      DATABASE_URL: postgresql://todouser:todopass@db:5432/todoapp
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  # API Server (Bun + Hono)
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: todo-api
    env_file:
      - .env.docker
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://todouser:todopass@db:5432/todoapp
      AUTH_SECRET: your-super-secret-key-change-in-production-min-32-chars
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    expose:
      - "3001"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'bun -e "fetch(''http://localhost:3001/health'').then(r => r.ok ? process.exit(0) : process.exit(1))" || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web App (React + Vite)
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: todo-web
    expose:
      - "80"

  # Nginx Proxy (Main Web Server)
  proxy:
    image: nginx:alpine
    container_name: todo-proxy
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - web
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: todo-network
